
sudo: required
services:
  - docker

before_install:
  - docker build -t charanrj0908/docker-project -f Dockerfile.dev

script:
  - docker run charanrj0908/docker-project  npm run test -- --coverage